---
- name: Automacao Provisionamento Virtual Machines em ambientes VMWARE
  hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - vmware


- name: Registra Host no Satellite
  hosts: new-hosts
  gather_facts: true
  remote_user: s_ansible
  become: True
  become_method: sudo
  become_user: root
  #sudo_user: root
  #sudo_exe: sudo
  #ask_pass: True
  roles:
    - satellite_register
