---
# tasks file for satellite_register

- name: Wait 1min for VMs to start
  wait_for:
    timeout: 120

- name: Add host
    add_host:
      name: "{{ network_ip_address }}"
      groups: new-hosts
